name: msaratwasel_user
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  google_maps_flutter: ^2.9.0
  google_fonts: ^6.2.1
  flutter_advanced_drawer: ^1.3.5
  glassmorphism: ^3.0.0
  phosphor_flutter: ^2.1.0
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  flutter_neumorphic_plus: ^3.3.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  auto_route: ^11.0.0
  go_router: ^17.0.0
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.2
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.0
  flutter_spinkit: ^5.2.2
  flutter_polyline_points: ^3.1.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  awesome_notifications: ^0.10.1
  dio: ^5.9.0
  retrofit: ^4.9.1
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  get_storage: ^2.1.1
  responsive_framework: ^1.4.0
  getwidget: ^4.0.0
  velocity_x: ^4.2.1
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  cached_network_image: ^3.4.1
  flutter_form_builder: ^10.2.0
  flutter_iconly: ^1.0.2
  ionicons: ^0.2.2
  rive: ^0.13.20
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  device_info_plus: ^12.3.0
  url_launcher: ^6.3.2
  syncfusion_flutter_pdf: ^31.2.16
  printing: ^5.14.2
  web_socket_channel: ^3.0.3
  socket_io_client: ^3.1.3
  jwt_decoder: ^2.0.1
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  permission_handler: ^12.0.1
  background_location: ^0.13.2
  remixicon: ^1.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/