import 'package:flutter/material.dart';
import 'package:msaratwasel_user/src/app/state/app_controller.dart';

class AppStrings {
  AppStrings._();

  static const _strings = {
    'ar': {
      'appName': 'مسارات واصل',
      'home': 'الرئيسية',
      'guardianGreeting': 'مرحباً، ولي الأمر',
      'activitiesTitle': 'الأنشطة والإشعارات',
      'activitiesSubtitle': 'آخر إعلانات وتحديثات المدرسة.',
      'viewAll': 'عرض الكل',
      'quickActionsTitle': 'خدمات سريعة',
      'kidsTitle': 'أبنائي',
      'busInfoTitle': 'معلومات الحافلة',
      'driverName': 'اسم السائق',
      'assistantName': 'اسم المساعد',
      'statusLabel': 'الحالة',
      'etaLabel': 'وصول متوقع',
      'visitSchoolSite': 'زيارة موقع المدرسة',
      'notAvailable': 'غير متاح',
      'tracking': 'التتبع',
      'notifications': 'الإشعارات',
      'messages': 'الرسائل',
      'more': 'المزيد',
      'dashboardTitle': 'حالة أبنائي الآن',
      'chooseStudent': 'الابناء', // Children in Arabic
      'busStatus': 'حالة الحافلة',
      'eta': 'الوقت المتوقع',
      'studentsOnBus': 'طلاب في الحافلة',
      'lastAlert': 'آخر تنبيه',
      'trackBus': 'تتبع الحافلة',
      'attendance': 'الحضور والغياب',
      'markAbsence': 'إبلاغ بعدم الذهاب',
      'attendanceHistory': 'سجل الحضور',
      'tripsHistory': 'سجل الرحلات',
      'today': 'اليوم',
      'route': 'المسار الحالي',
      'speed': 'السرعة',
      'distance': 'المسافة',
      'updated': 'تم التحديث',
      'minutesSuffix': 'دقيقة',
      'remainingTime': 'الوقت المتبقي',
      'kmh': 'كم/س',
      'km': 'كم',
      'ago': 'مضت',
      'typeAll': 'الكل',
      'writeMessage': 'اكتب رسالة...',
      'schoolInfo': 'معلومات المدرسة',
      'busDriver': 'سائق الحافلة',
      'busSupervisor': 'مشرفة الحافلة',
      'phoneNumber': 'رقم الجوال',
      'call': 'اتصال',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'enableNotifications': 'تفعيل الإشعارات',
      'addChild': 'إضافة طالب',
      'logout': 'تسجيل الخروج',
      'settings': 'الإعدادات',
      'studentInfo': 'بيانات الطالب',
      'busInfo': 'بيانات الحافلة',
      'driver': 'السائق',
      'supervisor': 'المشرفة',
      'contact': 'اتصال',
      'absenceOut': 'ذهاب فقط',
      'absenceIn': 'عودة فقط',
      'absenceFull': 'اليوم كامل',
      'selectDate': 'اختر التاريخ',
      'submit': 'إرسال',
      'cancel': 'إلغاء',
      'messagesWithSupervisor': 'محادثة مع المشرفة',
      'tripDelayed': 'متأخرة',
      'tripOnTime': 'في الموعد',
      'arrival': 'وصول',
      'checkIn': 'صعود',
      'checkOut': 'نزول',
      'busPlate': 'رقم اللوحة',
      'busNumber': 'رقم الحافلة',
      'contactDriver': 'اتصال بالسائق',
      'contactSupervisor': 'اتصال بالمشرفة',
      'absenceNote': 'ملاحظة (اختياري)',
      'createRequest': 'حفظ الطلب',
      'systemNotifications': 'إعدادات إشعارات الجهاز',
      'bus': 'الحافلة',
      'welcomeBack': 'مرحباً بك مجدداً',
      'signInToContinue': 'سجل دخولك للمتابعة',
      'civilId': 'الرقم المدني',
      'civilIdError': 'الرقم المدني لولي الامر',
      'phoneError': 'رقم جوال ولي الامر',
      'rememberMe': 'تذكرني',
      'forgotData': 'نسيت كلمة المرور؟',
      'login': 'تسجيل الدخول',
      'or': 'أو',
      'noAccount': 'ليس لديك حساب؟ ',
      'registerNow': 'سجل الآن',
      'loginError': 'بيانات الدخول غير صحيحة',
      'connectionError': 'حدث خطأ في الاتصال',
      'loading': 'جاري التحميل...',
      'requestAbsence': 'طلب غياب',
      'absenceLog': 'سجل الغياب',
      'absenceReason': 'السبب (اختياري)',
      'sendAbsenceRequest': 'إرسال طلب الغياب',
      'changePassword': 'تغيير كلمة المرور',
      'currentPassword': 'كلمة المرور الحالية',
      'newPassword': 'كلمة المرور الجديدة',
      'confirmPassword': 'تأكيد كلمة المرور الجديدة',
      'saveChanges': 'حفظ التغييرات',
      'passwordMismatch': 'كلمات المرور غير متطابقة',
      'passwordLengthError': 'يجب أن لا تقل عن 6 خانات',
      'fieldRequired': 'مطلوب',
      'passwordUpdatedSuccess': 'تم تغيير كلمة المرور بنجاح',
      'myKids': 'أبنائي',
      'account': 'الحساب',
      'profile': 'الملف الشخصي',
      'editProfile': 'تعديل البيانات الشخصية',
      'manageKids': 'إدارة الطلاب المسجلين',
      'application': 'التطبيق',
      'appearance': 'المظهر',
      'dark': 'داكن',
      'light': 'فاتح',
      'helpCenter': 'مركز المساعدة',
      'contactUs': 'تواصل معنا',
      'aboutApp': 'عن التطبيق',
      'canteen': 'المقصف',
      'support': 'الدعم',
      'forgotPasswordTitle': 'نسيت كلمة المرور؟',
      'forgotPasswordSubtitle': 'أدخل رقم الجوال لاستلام رابط إعادة التعيين.',
      'sendResetLink': 'إرسال رابط التحقق',
      'backToLogin': 'العودة لتسجيل الدخول',
      'resetLinkSent': 'تم إرسال رابط التحقق بنجاح',
      'enterValidPhone': 'يرجى إدخال رقم جوال صحيح',
      'otpVerification': 'رمز التحقق',
      'enterOtpSubtitle': 'أدخل الرمز المكون من 4 أرقام المرسل إلى جوالك.',
      'verify': 'تحقق',
      'resendCode': 'إعادة إرسال الرمز',
      'resendIn': 'إعادة الإرسال خلال',
      'otpError': 'الرمز غير صحيح',
      'guardianRole': 'ولي الأمر',
      'attendanceManagement': 'إدارة الحضور',
      'busTracking': 'تتبع الحافلة',
      'chat': 'الدردشة',
      'absenceType': 'نوع الغياب',
      'presentDays': 'أيام الحضور',
      'absentDays': 'أيام الغياب',
      'present': 'حاضر',
      'statusApproved': 'مقبول',
      'statusRejected': 'مرفوض',
      'statusPending': 'قيد المراجعة',
      'reasonHint': 'مثال: موعد طبي...',
      'noAbsenceHistory': 'لا يوجد سجل غياب',
      'noStudentsRegistered': 'لا يوجد أبناء مسجلون',
      'addStudentToStart': 'أضف طالباً للبدء في تتبع الرحلات',
      'greetingMorning': 'صباح الخير',
      'greetingAfternoon': 'مساء الخير',
      'greetingEvening': 'مساء الخير',
      'welcomeUser': 'مرحباً بك يا',
      'track': 'تتبع',
      'file': 'الملف',
      'studentGrade': 'الصف',
      'locationNoteHint': 'ملاحظة الموقع (مثال: البوابة الرئيسية)',
      'homeLocation': 'موقع المنزل',
      'setHomeLocation': 'تحديد موقع المنزل',
      'editHomeLocation': 'تعديل الموقع',
      'locationUpdated': 'تم تحديث الموقع بنجاح',
      'editLocation': 'تعديل الموقع',
      'searchLocation': 'ابحث عن موقع...',
      'confirmLocation': 'تأكيد الموقع',
      'changeChildrenLocation': 'تغيير موقع الابناء',
      'selectChildToChangeLocation': 'اختر الابن لتغيير موقعه',
      'privacyPolicy': 'السياسة والخصوصية',
      'complaintsBox': 'صندوق الشكاوى والمقترحات',
      'complaintMessageHint': 'اكتب نص الاقتراح أو الشكوى هنا...',
      'contactMethods': 'طرق التواصل',
      'socialMedia': 'حسابات التواصل',
      'website': 'الموقع الإلكتروني',
      'email': 'البريد الإلكتروني',
      'complaintSent': 'تم إرسال رسالتك بنجاح',
      'schoolName': 'اسم المدرسة',
      'aboutAppDescription':
          'تطبيق مسارات واصل هو الحل الأمثل لإدارة النقل المدرسي بفعالية وأمان. يتيح لأولياء الأمور متابعة أبنائهم وتلقي الإشعارات اللحظية، مما يضمن راحة البال وسلامة الطلاب.',
      'aboutCompanyTitle': 'عن شركة واصل',
      'aboutCompany':
          'شركة واصل للنقل المدرسي هي شركة رائدة في مجال خدمات النقل، تسعى لتقديم تجربة نقل آمنة ومريحة للطلاب مع توظيف أحدث التقنيات لضمان الجودة والموثوقية.',
      'developedBy': 'تم التطوير بواسطة',
      'locationChangeWarningTitle': 'تنبيه هام',
      'locationChangeWarningBody':
          'يرجى العلم بأنه في حال تغيير الموقع، يجب إبلاغ المدرسة قبل 48 ساعة من موعد التغيير لضمان ترتيبات النقل.',
      'proceed': 'متابعة',
      'version': 'الإصدار',
      'privacyIntroTitle': 'أولًا: المقدمة',
      'privacyIntroBody1':
          'هذه الوثيقة تمثل اتفاقًا قانونيًا بين مستخدمي التطبيق (ولي الأمر، الطالب، السائق، المشرفة، المعلم، المشرف الميداني، المدرسة) وبين إدارة التطبيق.',
      'privacyIntroBody2':
          'باستخدام التطبيق، يقر جميع المستخدمين بموافقتهم على هذه السياسة والالتزام بها.',
      'privacyDataCollectionTitle': 'ثانيًا: جمع البيانات',
      'privacyStudentDataTitle': 'بيانات الطالب:',
      'privacyStudentData1': 'الاسم الكامل',
      'privacyStudentData2': 'الرقم المدرسي',
      'privacyStudentData3': 'الرقم المدني',
      'privacyStudentData4': 'صورة الطالب',
      'privacyStudentData5': 'صورة المنزل',
      'privacyStudentData6': 'الموقع الجغرافي للحافلة',
      'privacyStudentData7': 'سجل الحضور والانصراف عبر الباركود',
      'privacyOtherDataTitle': 'بيانات أخرى:',
      'privacyOtherData1':
          'بيانات ولي الأمر: الاسم، رقم الهاتف، البريد الإلكتروني، رقم الهوية المدنية.',
      'privacyOtherData2':
          'بيانات السائق والمشرفين والمعلمين: الاسم، رقم الهوية/الوظيفة، بيانات الاتصال.',
      'privacyOtherData3':
          'بيانات تقنية: سجل الدخول، استخدام الباركود، الموقع الجغرافي للحافلة.',
      'privacyDataUsageTitle': 'ثالثًا: استخدام البيانات',
      'privacyDataUsage1': 'ضمان سلامة الطالب أثناء النقل المدرسي.',
      'privacyDataUsage2': 'تمكين ولي الأمر من متابعة حالة الطالب.',
      'privacyDataUsage3': 'إدارة عمليات النقل المدرسي بكفاءة.',
      'privacyDataUsage4': 'إصدار تقارير للمدرسة والمشرفين.',
      'privacyDataUsage5': 'لا تُستخدم البيانات لأي أغراض تجارية أو دعائية.',
      'privacyDataProtectionTitle': 'رابعًا: حماية البيانات',
      'privacyDataProtection1':
          'تخزين البيانات في خوادم آمنة باستخدام تقنيات التشفير.',
      'privacyDataProtection2': 'تقييد الوصول للبيانات حسب صلاحيات المستخدم.',
      'privacyDataProtection3': 'مراجعة دورية لإجراءات الأمان.',
      'privacyDataProtection4':
          'عدم مشاركة البيانات مع أطراف ثالثة إلا بموافقة المدرسة أو وفق القانون.',
      'privacyUserRightsTitle': 'خامسًا: حقوق المستخدمين',
      'privacyUserRights1': 'الحق في الاطلاع على بياناتهم.',
      'privacyUserRights2': 'الحق في طلب تصحيح أو حذف بيانات غير دقيقة.',
      'privacyUserRights3':
          'الحق في الاعتراض على استخدام بياناتهم لأغراض غير تعليمية.',
      'privacyUserObligationsTitle': 'سادسًا: التزامات المستخدمين',
      'privacyUserObligations1':
          'استخدام التطبيق فقط للأغراض التعليمية والنقل المدرسي.',
      'privacyUserObligations2': 'عدم مشاركة بيانات الدخول مع أطراف أخرى.',
      'privacyUserObligations3':
          'الالتزام بالقوانين المحلية المتعلقة بحماية البيانات.',
      'privacyLegalLiabilityTitle': 'سابعًا: المسؤولية القانونية',
      'privacyLegalLiability1':
          'التطبيق غير مسؤول عن أي استخدام غير مصرح به من قبل المستخدمين.',
      'privacyLegalLiability2':
          'المدرسة تتحمل مسؤولية إدارة صلاحيات المستخدمين.',
      'privacyLegalLiability3':
          'أي خرق أمني سيتم التعامل معه وفق القوانين المحلية (بما في ذلك المرسوم السلطاني رقم 6/2022 بشأن حماية البيانات الشخصية في سلطنة عمان).',
      'privacyAmendmentsTitle': 'ثامنًا: التعديلات',
      'privacyAmendments1':
          'تحتفظ إدارة التطبيق بحق تعديل هذه السياسة بما يتوافق مع القوانين والتطورات التقنية.',
      'privacyAmendments2': 'سيتم إخطار المستخدمين بأي تغييرات جوهرية.',
      'privacyConsentTitle': 'تاسعًا: الموافقة',
      'privacyConsentBody':
          'باستخدام التطبيق، يوافق جميع المستخدمين على هذه السياسة ويلتزمون بها.',
      'privacySimplifiedTitle': '📱 نسخة مبسطة للمستخدمين',
      'privacyQ1': 'لماذا نجمع البيانات؟',
      'privacyA1':
          '- لضمان سلامة الطالب أثناء الرحلة.\n- لمساعدة ولي الأمر على متابعة وصول وخروج الطالب.\n- لتسهيل عمل السائق والمشرفة والمعلم والمشرف الميداني.',
      'privacyQ2': 'ما هي البيانات التي نستخدمها؟',
      'privacyA2':
          '- اسم الطالب ورقمه المدرسي.\n- الرقم المدني وصورة الطالب للتأكد من الهوية.\n- صورة المنزل والموقع الجغرافي للحافلة.\n- سجل حضور وانصراف الطالب عبر الباركود.\n- بيانات ولي الأمر للتواصل.\n- بيانات السائق والمشرفين والمعلمين.',
      'privacyQ3': 'كيف نحمي بياناتك؟',
      'privacyA3':
          '- نخزن المعلومات في أنظمة آمنة ومشفرة.\n- لا نشارك بياناتك مع أي طرف خارجي إلا بموافقة المدرسة أو إذا طلب القانون ذلك.\n- نحدد صلاحيات الدخول بحيث يرى كل مستخدم فقط ما يحتاجه لعمله.',
      'privacyQ4': 'حقوقك',
      'privacyA4':
          '- يمكنك الاطلاع على بياناتك.\n- يمكنك طلب تعديل أو حذف بيانات غير صحيحة.\n- بياناتك لن تُستخدم لأي أغراض تجارية أو دعائية.',
      'privacyQ5': 'التزاماتك',
      'privacyA5':
          '- استخدام التطبيق فقط للنقل المدرسي.\n- عدم مشاركة حسابك أو بيانات الدخول مع الآخرين.\n- الالتزام بالقوانين المحلية الخاصة بحماية البيانات.',
    },
    'en': {
      'appName': 'Msarat Wasel',
      'home': 'Home',
      'guardianGreeting': 'Hello, Guardian',
      'activitiesTitle': 'Activities & alerts',
      'activitiesSubtitle': 'Latest school updates and announcements.',
      'viewAll': 'View all',
      'quickActionsTitle': 'Quick actions',
      'kidsTitle': 'My kids',
      'busInfoTitle': 'Bus info',
      'driverName': 'Driver name',
      'assistantName': 'Assistant name',
      'statusLabel': 'Status',
      'etaLabel': 'ETA',
      'visitSchoolSite': 'Visit school website',
      'notAvailable': 'Not available',
      'tracking': 'Tracking',
      'notifications': 'Notifications',
      'messages': 'Messages',
      'more': 'More',
      'dashboardTitle': 'My kids status',
      'chooseStudent': 'Children',
      'busStatus': 'Bus status',
      'eta': 'ETA',
      'studentsOnBus': 'Students on bus',
      'lastAlert': 'Last alert',
      'trackBus': 'Track bus',
      'attendance': 'Attendance',
      'markAbsence': 'Report absence',
      'attendanceHistory': 'Attendance log',
      'tripsHistory': 'Trip history',
      'today': 'Today',
      'route': 'Current route',
      'speed': 'Speed',
      'distance': 'Distance',
      'updated': 'Updated',
      'minutesSuffix': 'min',
      'remainingTime': 'Remaining time',
      'kmh': 'km/h',
      'km': 'km',
      'ago': 'ago',
      'typeAll': 'All',
      'writeMessage': 'Write a message...',
      'schoolInfo': 'School Information',
      'busDriver': 'Bus Driver',
      'busSupervisor': 'Bus Supervisor',
      'phoneNumber': 'Phone Number',
      'call': 'Call',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'enableNotifications': 'Enable notifications',
      'addChild': 'Add child',
      'logout': 'Logout',
      'settings': 'Settings',
      'studentInfo': 'Student info',
      'busInfo': 'Bus info',
      'driver': 'Driver',
      'supervisor': 'Supervisor',
      'contact': 'Call',
      'absenceOut': 'Morning only',
      'absenceIn': 'Return only',
      'absenceFull': 'Full day',
      'selectDate': 'Pick date',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'messagesWithSupervisor': 'Chat with supervisor',
      'tripDelayed': 'Delayed',
      'tripOnTime': 'On time',
      'arrival': 'Arrival',
      'checkIn': 'Check-in',
      'checkOut': 'Check-out',
      'busPlate': 'Plate',
      'busNumber': 'Bus number',
      'contactDriver': 'Call driver',
      'contactSupervisor': 'Call supervisor',
      'absenceNote': 'Note (optional)',
      'createRequest': 'Save request',
      'systemNotifications': 'System notification settings',
      'bus': 'Bus',
      'welcomeBack': 'Welcome back',
      'signInToContinue': 'Sign in to continue',
      'civilId': 'Civil ID',
      'civilIdError': 'Guardian Civil ID',

      'phoneError': 'Guardian Phone Number',
      'rememberMe': 'Remember me',
      'forgotData': 'Forgot Password?',
      'login': 'Login',
      'or': 'OR',
      'noAccount': 'Don\'t have an account?',
      'registerNow': 'Register now',
      'loginError': 'Incorrect login details',
      'connectionError': 'Connection error',
      'loading': 'Loading...',
      'requestAbsence': 'Request absence',
      'absenceLog': 'Absence log',
      'absenceReason': 'Reason (optional)',
      'sendAbsenceRequest': 'Submit absence request',
      'changePassword': 'Change password',
      'currentPassword': 'Current password',
      'newPassword': 'New password',
      'confirmPassword': 'Confirm new password',
      'saveChanges': 'Save changes',
      'passwordMismatch': 'Passwords do not match',
      'passwordLengthError': 'Must be at least 6 characters',
      'fieldRequired': 'Required',
      'passwordUpdatedSuccess': 'Password updated successfully',
      'myKids': 'My kids',
      'account': 'Account',
      'profile': 'Profile',
      'editProfile': 'Edit personal info',
      'manageKids': 'Manage registered students',
      'application': 'Application',
      'appearance': 'Appearance',
      'dark': 'Dark',
      'light': 'Light',
      'helpCenter': 'Help center',
      'contactUs': 'Contact us',
      'aboutApp': 'About app',
      'canteen': 'Canteen',
      'support': 'Support',
      'forgotPasswordTitle': 'Forgot Password?',
      'forgotPasswordSubtitle': 'Enter phone number to get reset link.',
      'sendResetLink': 'Send Reset Link',
      'backToLogin': 'Back to Login',
      'resetLinkSent': 'Reset link sent successfully',
      'enterValidPhone': 'Please enter a valid phone number',
      'otpVerification': 'Verification Code',
      'enterOtpSubtitle': 'Enter the 4-digit code sent to your phone.',
      'verify': 'Verify',
      'resendCode': 'Resend Code',
      'resendIn': 'Resend in',
      'otpError': 'Invalid code',
      'guardianRole': 'Guardian',
      'attendanceManagement': 'Attendance Management',
      'busTracking': 'Bus Tracking',
      'chat': 'Chat',
      'absenceType': 'Absence Type',
      'presentDays': 'Days Present',
      'absentDays': 'Days Absent',
      'present': 'Present',
      'statusApproved': 'Approved',
      'statusRejected': 'Rejected',
      'statusPending': 'Pending',
      'reasonHint': 'Ex: Doctor appointment...',
      'noAbsenceHistory': 'No absence history',
      'noStudentsRegistered': 'No students registered',
      'addStudentToStart': 'Add a student to start tracking',
      'greetingMorning': 'Good Morning',
      'greetingAfternoon': 'Good Afternoon',
      'greetingEvening': 'Good Evening',
      'welcomeUser': 'Welcome,',
      'track': 'Track',
      'file': 'Profile',
      'studentGrade': 'Grade',
      'locationNoteHint': 'Location Note (e.g. Main Gate)',
      'homeLocation': 'Home Location',
      'setHomeLocation': 'Set Home Location',
      'editHomeLocation': 'Edit Location',
      'locationUpdated': 'Location updated successfully',
      'editLocation': 'Edit Location',
      'searchLocation': 'Search location...',
      'confirmLocation': 'Confirm Location',
      'changeChildrenLocation': 'Change Children Location',
      'selectChildToChangeLocation': 'Select Child to Change Location',
      'privacyPolicy': 'Privacy Policy',
      'complaintsBox': 'Complaints & Suggestions Box',
      'complaintMessageHint': 'Write your suggestion or complaint here...',
      'contactMethods': 'Contact Methods',
      'socialMedia': 'Social Media',
      'website': 'Website',
      'email': 'Email',
      'complaintSent': 'Your message has been sent successfully',
      'schoolName': 'School Name',
      'aboutAppDescription':
          'Msarat Wasel is the ideal solution for managing school transport effectively and safely. It allows parents to track their children and receive real-time notifications, ensuring peace of mind and student safety.',
      'aboutCompanyTitle': 'About Wasel Company',
      'aboutCompany':
          'Wasel School Transport is a leading company in transport services, striving to provide a safe and comfortable transport experience for students while employing the latest technologies to ensure quality and reliability.',
      'developedBy': 'Developed by',
      'locationChangeWarningTitle': 'Important Notice',
      'locationChangeWarningBody':
          'Please note that if the location is changed, the school must be notified 48 hours prior to the change to ensure transport arrangements.',
      'proceed': 'Proceed',
      'version': 'Version',
      'privacyIntroTitle': 'First: Introduction',
      'privacyIntroBody1':
          'This document represents a legal agreement between the application users (Guardian, Student, Driver, Supervisor, Teacher, Field Supervisor, School) and the application administration.',
      'privacyIntroBody2':
          'By using the application, all users acknowledge their agreement to this policy and commitment to it.',
      'privacyDataCollectionTitle': 'Second: Data Collection',
      'privacyStudentDataTitle': 'Student Data:',
      'privacyStudentData1': 'Full Name',
      'privacyStudentData2': 'School ID',
      'privacyStudentData3': 'Civil ID',
      'privacyStudentData4': 'Student Photo',
      'privacyStudentData5': 'Home Photo',
      'privacyStudentData6': 'Bus Geographic Location',
      'privacyStudentData7': 'Attendance Log via Barcode',
      'privacyOtherDataTitle': 'Other Data:',
      'privacyOtherData1':
          'Guardian Data: Name, Phone Number, Email, Civil ID.',
      'privacyOtherData2':
          'Driver, Supervisor, and Teacher Data: Name, ID/Job Number, Contact Info.',
      'privacyOtherData3':
          'Technical Data: Login Log, Barcode Usage, Bus Geographic Location.',
      'privacyDataUsageTitle': 'Third: Data Usage',
      'privacyDataUsage1': 'Ensuring student safety during school transport.',
      'privacyDataUsage2': 'Enabling guardians to track student status.',
      'privacyDataUsage3': 'Managing school transport operations efficiently.',
      'privacyDataUsage4': 'Issuing reports for the school and supervisors.',
      'privacyDataUsage5':
          'Data is not used for any commercial or promotional purposes.',
      'privacyDataProtectionTitle': 'Fourth: Data Protection',
      'privacyDataProtection1':
          'Storing data in secure servers using encryption technologies.',
      'privacyDataProtection2':
          'Restricting access to data according to user permissions.',
      'privacyDataProtection3': 'Periodic review of security procedures.',
      'privacyDataProtection4':
          'Not sharing data with third parties unless approved by the school or required by law.',
      'privacyUserRightsTitle': 'Fifth: User Rights',
      'privacyUserRights1': 'The right to access their data.',
      'privacyUserRights2':
          'The right to request correction or deletion of inaccurate data.',
      'privacyUserRights3':
          'The right to object to the use of their data for non-educational purposes.',
      'privacyUserObligationsTitle': 'Sixth: User Obligations',
      'privacyUserObligations1':
          'Using the application only for educational and school transport purposes.',
      'privacyUserObligations2':
          'Not sharing login credentials with other parties.',
      'privacyUserObligations3':
          'Adhering to local laws regarding data protection.',
      'privacyLegalLiabilityTitle': 'Seventh: Legal Liability',
      'privacyLegalLiability1':
          'The application is not responsible for any unauthorized use by users.',
      'privacyLegalLiability2':
          'The school bears the responsibility of managing user permissions.',
      'privacyLegalLiability3':
          'Any security breach will be dealt with according to local laws (including Royal Decree No. 6/2022 on Personal Data Protection in Oman).',
      'privacyAmendmentsTitle': 'Eighth: Amendments',
      'privacyAmendments1':
          'The application administration reserves the right to amend this policy in accordance with laws and technical developments.',
      'privacyAmendments2':
          'Users will be notified of any substantial changes.',
      'privacyConsentTitle': 'Ninth: Consent',
      'privacyConsentBody':
          'By using the application, all users agree to this policy and adhere to it.',
      'privacySimplifiedTitle': '📱 Simplified Version for Users',
      'privacyQ1': 'Why do we collect data?',
      'privacyA1':
          '- To ensure student safety during the trip.\n- To help the guardian track the student\'s arrival and departure.\n- To facilitate the work of the driver, supervisor, teacher, and field supervisor.',
      'privacyQ2': 'What data do we use?',
      'privacyA2':
          '- Student name and school number.\n- Civil ID and student photo for identity verification.\n- Home photo and bus geographic location.\n- Student attendance log via barcode.\n- Guardian data for communication.\n- Driver, supervisor, and teacher data.',
      'privacyQ3': 'How do we protect your data?',
      'privacyA3':
          '- We store information in secure and encrypted systems.\n- We do not share your data with any external party unless approved by the school or required by law.\n- We define access permissions so each user only sees what they need for their work.',
      'privacyQ4': 'Your Rights',
      'privacyA4':
          '- You can access your data.\n- You can request correction or deletion of incorrect data.\n- Your data will not be used for any commercial or promotional purposes.',
      'privacyQ5': 'Your Obligations',
      'privacyA5':
          '- Use the application only for school transport.\n- Do not share your account or login details with others.\n- Adhere to local laws regarding data protection.',
    },
  };

  static String of(BuildContext context, String key) {
    final locale = AppScope.of(context).locale;
    final lang = locale.languageCode;
    return _strings[lang]?[key] ?? _strings['ar']![key] ?? key;
  }
}

extension LocalizationX on BuildContext {
  String t(String key) => AppStrings.of(this, key);
}
