import 'package:flutter/material.dart';

import 'package:msaratwasel_user/src/app/state/app_controller.dart';

class AppStrings {
  AppStrings._();

  static const _strings = {
    'ar': {
      'appName': 'مسارات واصل',
      'home': 'الرئيسية',
      'guardianGreeting': 'مرحباً، ولي الأمر',
      'activitiesTitle': 'الأنشطة والإشعارات',
      'activitiesSubtitle': 'آخر إعلانات وتحديثات المدرسة.',
      'viewAll': 'عرض الكل',
      'quickActionsTitle': 'خدمات سريعة',
      'kidsTitle': 'أبنائي',
      'busInfoTitle': 'معلومات الحافلة',
      'driverName': 'اسم السائق',
      'assistantName': 'اسم المساعد',
      'statusLabel': 'الحالة',
      'etaLabel': 'وصول متوقع',
      'visitSchoolSite': 'زيارة موقع المدرسة',
      'notAvailable': 'غير متاح',
      'tracking': 'التتبع',
      'notifications': 'الإشعارات',
      'messages': 'الرسائل',
      'more': 'المزيد',
      'dashboardTitle': 'حالة أبنائي الآن',
      'chooseStudent': 'اختر الطالب',
      'busStatus': 'حالة الحافلة',
      'eta': 'الوقت المتوقع',
      'studentsOnBus': 'طلاب في الحافلة',
      'lastAlert': 'آخر تنبيه',
      'trackBus': 'تتبع الحافلة',
      'attendance': 'الحضور والغياب',
      'markAbsence': 'إبلاغ بعدم الذهاب',
      'attendanceHistory': 'سجل الحضور',
      'tripsHistory': 'سجل الرحلات',
      'today': 'اليوم',
      'route': 'المسار الحالي',
      'speed': 'السرعة',
      'distance': 'المسافة',
      'updated': 'تم التحديث',
      'minutesSuffix': 'دقيقة',
      'kmh': 'كم/س',
      'km': 'كم',
      'ago': 'مضت',
      'typeAll': 'الكل',
      'writeMessage': 'اكتب رسالة...',
      'send': 'إرسال',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'enableNotifications': 'تفعيل الإشعارات',
      'addChild': 'إضافة طالب',
      'logout': 'تسجيل الخروج',
      'settings': 'الإعدادات',
      'studentInfo': 'بيانات الطالب',
      'busInfo': 'بيانات الحافلة',
      'driver': 'السائق',
      'supervisor': 'المشرفة',
      'contact': 'اتصال',
      'absenceOut': 'ذهاب فقط',
      'absenceIn': 'عودة فقط',
      'absenceFull': 'اليوم كامل',
      'selectDate': 'اختر التاريخ',
      'submit': 'إرسال',
      'cancel': 'إلغاء',
      'messagesWithSupervisor': 'محادثة مع المشرفة',
      'tripDelayed': 'متأخرة',
      'tripOnTime': 'في الموعد',
      'arrival': 'وصول',
      'checkIn': 'صعود',
      'checkOut': 'نزول',
      'busPlate': 'رقم اللوحة',
      'busNumber': 'رقم الحافلة',
      'contactDriver': 'اتصال بالسائق',
      'contactSupervisor': 'اتصال بالمشرفة',
      'absenceNote': 'ملاحظة (اختياري)',
      'createRequest': 'حفظ الطلب',
      'systemNotifications': 'إعدادات إشعارات الجهاز',
      'homeLocation': 'المنزل',
      'bus': 'الحافلة',
      'welcomeBack': 'مرحباً بك مجدداً',
      'signInToContinue': 'سجل دخولك للمتابعة',
      'civilId': 'الرقم المدني',
      'civilIdError': 'الرقم المدني لولي الامر',
      'phoneNumber': 'رقم الجوال',
      'phoneError': 'رقم جوال ولي الامر',
      'rememberMe': 'تذكرني',
      'forgotData': 'نسيت البيانات؟',
      'login': 'تسجيل الدخول',
      'or': 'أو',
      'noAccount': 'ليس لديك حساب؟ ',
      'registerNow': 'سجل الآن',
      'loginError': 'بيانات الدخول غير صحيحة',
      'connectionError': 'حدث خطأ في الاتصال',
      'loading': 'جاري التحميل...',
    },
    'en': {
      'appName': 'Msarat Wasel',
      'home': 'Home',
      'guardianGreeting': 'Hello, Guardian',
      'activitiesTitle': 'Activities & alerts',
      'activitiesSubtitle': 'Latest school updates and announcements.',
      'viewAll': 'View all',
      'quickActionsTitle': 'Quick actions',
      'kidsTitle': 'My kids',
      'busInfoTitle': 'Bus info',
      'driverName': 'Driver name',
      'assistantName': 'Assistant name',
      'statusLabel': 'Status',
      'etaLabel': 'ETA',
      'visitSchoolSite': 'Visit school website',
      'notAvailable': 'Not available',
      'tracking': 'Tracking',
      'notifications': 'Notifications',
      'messages': 'Messages',
      'more': 'More',
      'dashboardTitle': 'My kids status',
      'chooseStudent': 'Select student',
      'busStatus': 'Bus status',
      'eta': 'ETA',
      'studentsOnBus': 'Students on bus',
      'lastAlert': 'Last alert',
      'trackBus': 'Track bus',
      'attendance': 'Attendance',
      'markAbsence': 'Report absence',
      'attendanceHistory': 'Attendance log',
      'tripsHistory': 'Trip history',
      'today': 'Today',
      'route': 'Current route',
      'speed': 'Speed',
      'distance': 'Distance',
      'updated': 'Updated',
      'minutesSuffix': 'min',
      'kmh': 'km/h',
      'km': 'km',
      'ago': 'ago',
      'typeAll': 'All',
      'writeMessage': 'Write a message...',
      'send': 'Send',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'enableNotifications': 'Enable notifications',
      'addChild': 'Add child',
      'logout': 'Logout',
      'settings': 'Settings',
      'studentInfo': 'Student info',
      'busInfo': 'Bus info',
      'driver': 'Driver',
      'supervisor': 'Supervisor',
      'contact': 'Call',
      'absenceOut': 'Morning only',
      'absenceIn': 'Return only',
      'absenceFull': 'Full day',
      'selectDate': 'Pick date',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'messagesWithSupervisor': 'Chat with supervisor',
      'tripDelayed': 'Delayed',
      'tripOnTime': 'On time',
      'arrival': 'Arrival',
      'checkIn': 'Check-in',
      'checkOut': 'Check-out',
      'busPlate': 'Plate',
      'busNumber': 'Bus number',
      'contactDriver': 'Call driver',
      'contactSupervisor': 'Call supervisor',
      'absenceNote': 'Note (optional)',
      'createRequest': 'Save request',
      'systemNotifications': 'System notification settings',
      'homeLocation': 'Home',
      'bus': 'Bus',
      'welcomeBack': 'Welcome back',
      'signInToContinue': 'Sign in to continue',
      'civilId': 'Civil ID',
      'civilIdError': 'Guardian Civil ID',
      'phoneNumber': 'Phone number',
      'phoneError': 'Guardian Phone Number',
      'rememberMe': 'Remember me',
      'forgotData': 'Forgot data?',
      'login': 'Login',
      'or': 'OR',
      'noAccount': 'Don\'t have an account?',
      'registerNow': 'Register now',
      'loginError': 'Incorrect login details',
      'connectionError': 'Connection error',
      'loading': 'Loading...',
    },
  };

  static String of(BuildContext context, String key) {
    final locale = AppScope.of(context).locale;
    final lang = locale.languageCode;
    return _strings[lang]?[key] ?? _strings['ar']![key] ?? key;
  }
}

extension LocalizationX on BuildContext {
  String t(String key) => AppStrings.of(this, key);
}
