// File Generated by Assistant based on project configuration.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxoVpA2rapNIRtpa-cRTgwl_ZIhlrjvrU',
    appId: '1:893934602338:android:0c56e41b38971585fea93b',
    messagingSenderId: '893934602338',
    projectId: 'msarart-wasel',
    storageBucket: 'msarart-wasel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt0cCMmVWwYJu3d-6ufrB5550Xd6tzt6A',
    appId: '1:893934602338:ios:e56af9483831144cfea93b',
    messagingSenderId: '893934602338',
    projectId: 'msarart-wasel',
    storageBucket: 'msarart-wasel.firebasestorage.app',
    iosBundleId: 'com.msaratwasel.user',
  );
}
